# .streamlit/secrets.toml

[snowflake]
user = "HugoAsaga"
role = "ACCOUNTADMIN"
password = "ansvpwSab8"
account = "kra58564.us-east-1"
warehouse = "TRIGGO_EXAMPLES_WAREHOUSE"
database = "TRIGGO_EXAMPLES_DATABASE"
schema = "ANALYTICS"